BO:
  method: evidence
  evidence:
    max_steps: 100
    # cobaya_model_file: ./examples/cosmo_input/LCDM_2D.yaml
    # external_model: model.py
    acq_goal: 1e-8
    acq_batch_size: 1
    feedback_lvl: 1
    init_strat: Sobol
    ninit: 4
    gpfit_step: 1
    save: True
    save_file: 'run_data'
    save_step: 5
    ns_step: 10
    seed: 0
    feedback_lvl: 1
GP:
  method: fullybayesian
  fullybayesian:
    warmup_steps: 256
    num_samples: 256
    thinning: 16
    vmap_size: 8
    standardise_y: True
    noise: 1e-6
    kernel: rbf
    min_lengthscale: 1e-3
    max_lengthscale: 100.
NS:
  method: 'jaxns'
  jaxns:
    ns_dlogz_goal: 0.1
    #upper_lower: False
    ns_max_call: 1e5
    ns_final_dlogz: 0.01
  dynesty:
    dlogz_goal: 0.1
    upper_lower: True
    max_call: 1e5
    final_ns_dlogz: 0.01
ACQ:
  method: 'WIPV'
  WIPV:
    num_samples: 512
    warmup_steps: 512
    thinning: 16
    progress_bar: True
    verbose: False
  EI:
    zeta: 0.
optimizer:
  method: 'scipy_bh'
  bobyqa:
    seek_global_minimum: False
  scipy_bh: 
    stepsize: 0.2
    niter: 15
    minimizer_kwargs:
      method: L-BFGS-B  
  optax:
    steps: 100
    start_learning_rate: 1e-2
    n_restarts: 4
    jump_sdev: 0.1

